### ISSUE TITLE
gulpssh.exec "npm install" keep hanging

### ISSUE THREAD

**Issue by tectual** [teambition/gulp-ssh#11]
Firstly Thank You!

I am trying to automate my deployments and using: "gulp-ssh": "^0.3.3" and have something like this:
```
ssh.exec [ "cd /var/www/release_folder", "git pull", "npm install"], {filePath: 'gulp.ssh.log'}
```
Output:
```
[21:55:48] gulp-ssh :: Executing :: cd /var/www/release_folder
[21:55:49] gulp-ssh :: Executing :: npm install
[21:55:50] 'api:deploy' errored after 16 s
[21:55:50] Error in plugin 'gulp-ssh'
Message:
    npm
```
It keeps hanging and no error in my log file. Am I missing something? If I run the `cd /var/www/release_folder && npm install` command manually in my shell it works perfect.

**Comment by zensh** [comment]
`exec` can not change directory as this issue: https://github.com/mscdex/ssh2/issues/186

You should ues `shell`:

```js
gulp.task('shell', function () {
  return gulpSSH
    .shell(['cd /home/thunks', 'git pull', 'npm install', 'npm update', 'npm test'], {filePath: 'shell.log'})
    .pipe(gulp.dest('logs'));
});
```

**Comment by tectual** [comment]
Thanks! tested & perfect!
