### ISSUE TITLE
Is there an sftp "progress" event I can connect to?

### ISSUE THREAD

**Issue by skyzyx** [teambition/gulp-ssh#12]
It would be great if I could get a sense of how much longer, and/or where in the upload/download process, the SFTP action has.

**Comment by zensh** [comment]
demo:

```js
gulp.task('sftp-read', function () {
  return gulpSSH.sftp('read', 'pm2.json')
    .on('data', function (chunk) {/*...do it*/})
    .pipe(gulp.dest(''));
});
```

You can  calculate process precent (chunk size / total size) by youself.

**Comment by 0xorial** [comment]
Could you provide demo code for 'write'? I tried similar approach as here, but callback was called only once in the very end..

**Comment by 0xorial** [comment]
I have added a pull request with 'progress' stuff (dependent on pull request in ssh2-streams).

P.S. This is first time I am trying to contribute to multiple projects 'at once', so not 100% sure I did everything right...
