### ISSUE TITLE
exec cd don`t work

### ISSUE THREAD

**Issue by pdarscht** [teambition/gulp-ssh#13]
running this example:
```
gulp.task('test2', function () {
  return gulpSSH
    .exec(['date','hostname', 'cd /opt/app/', 'pwd', 'ls -a'],
             {filePath: 'commands.log'})
    .pipe(gulp.dest('logs'));
});
```

leaves in the log:
```
Fri Mar 20 15:12:35 UTC 2015
s21
/home/operador
.
..
.bash_history
.bash_logout
.bash_profile
.bashrc
```

that means, that everything works fine unless the "change directory" command. 
Can you help me?

**Comment by zensh** [comment]
https://github.com/teambition/gulp-ssh/issues/4

**Comment by pdarscht** [comment]
excuse me, I can´t understand your point... is it a bug or am I doing something wrong?

**Comment by zensh** [comment]
use `shell` instead of `exec`
