### ISSUE TITLE
Connection closes without any warning

### ISSUE THREAD

**Issue by chris-equis** [teambition/gulp-ssh#15]
Guys,
 I want to execute some commands on a remote server that I'm connecting through SSH with private/public keys.

The configuration is pretty basic:

```javascript
gulpSSH = require('gulp-ssh')({
  ignoreErrors: false,
  sshConfig: {
    // config.ssh is an Object that have hostname and username properties
    host: config.ssh.hostname,
    username: config.ssh.username,
    port: 22
  }
});
```

and the task, the in the same basic manner
```javascript
gulp.task('deploy-run', function() {
  return gulpSSH
    .shell(['mkdir x'], {filePath: 'ssh.log'})
    .pipe(dest('.logs'));
});
```

what console outputs when I type `gulp deploy-run` is
```
$ gulp deploy-run
Using gulpfile /<path-to-project>/gulpfile.js
Starting 'deploy-run'...
gulp-ssh :: Connect...
gulp-ssh :: Close
```
`ssh.log` file is created in `./.logs` but it has no content, unfortunately :(

Is there any issue with **gulp-ssh** or the configuration?

**Comment by zensh** [comment]
connection is failure. maybe some error in your username/password?

**Comment by chris-equis** [comment]
I'm authenticate with SSH key. From terminal it works just fine, from gulp plugin it does not.

**Comment by zensh** [comment]
This plugin should refactor with [ssh2-streams](https://github.com/mscdex/ssh2-streams), I will do it this weekend.

**Comment by zensh** [comment]
Hi, v0.4.0 released, it work well in my PC.

**Comment by chris-equis** [comment]
I will try also today or tomorrow. Thank you!
