### ISSUE TITLE
How do I close the connection?

### ISSUE THREAD

**Issue by 3m0** [teambition/gulp-ssh#18]
I don't see anywhere in the documentation how do I close the connection. When I run my gulp script it starts the ssh connection, runs the commands and hangs, making me press CTRL+C to stop the script.

**Comment by zensh** [comment]
Hi, v0.4.0 released, added `close` method.

In fact, it should auto close https://github.com/teambition/gulp-ssh/blob/master/index.js#L63, unless one more gulp instance used in your work.
