### ISSUE TITLE
Any way to log data during each command instead of the full data log at the end?

### ISSUE THREAD

**Issue by icd2k3** [teambition/gulp-ssh#33]
I have a gulp-ssh task that is setup like this:

    return gulpSSH
        .shell(['cd /mydir', 'git pull', 'npm install', 'gulp build'])
        .on('data', function(file) {
            console.log(file.contents.toString());
        });

The problem here is that ALL the data is logged AFTER all the tasks have run. Is there any way to display the data/logs as the tasks are being executed?

Thanks for the script and any suggestions!

**Comment by grundera** [comment]
Hi, try this:
```javascript
return gulpSSH
    .shell(['cd /mydir', 'git pull', 'npm install', 'gulp build'])
    .on('ssh2Data', function (data) {
        process.stdout.write(data.toString());
    });
```

**Comment by Luchillo** [comment]
@grundera That totally works, very very happy, though would like to be able to config the remote starting path in the configs instead of the '/' folder, should be able to close this issue.
