### ISSUE TITLE
Only transfer files that are timestamped as newer?

### ISSUE THREAD

**Issue by kmh3785** [teambition/gulp-ssh#37]
I'm trying to use gulp-ssh in conjunction with gulp-newer to only transfer files that are stamped as newer than the last transfer. Am I missing something here? This block transfers everything, not just updated files.

gulp.task('deploy-prod', function () {
     return gulp.src(['./'+build_dir+'wp-content/**/*'])
      .pipe(newer(prod_content_dir+'**/*'))
      .pipe(gulpSSH.dest(prod_content_dir))
});

**Comment by zensh** [comment]
How do gulp-newer detect remote file?
