### ISSUE TITLE
Does not work with .ssh/config

### ISSUE THREAD

**Issue by aluminium1989** [teambition/gulp-ssh#40]
My config example:

Host home
HostName home
Port xxxx
User xxxx

Authentication by public key.

**Comment by aluminium1989** [comment]
Will setting concrete IdentityFile resolve this problem?

**Comment by zensh** [comment]
Here is config example:
```js
var config = {
  host: '192.168.0.21',
  port: 22,
  username: 'iojs',
  privateKey: fs.readFileSync('/Users/zensh/.ssh/id_rsa')
}

var gulpSSH = new GulpSSH({
  ignoreErrors: false,
  sshConfig: config
})
```

Why didn't you read README?

**Comment by zensh** [comment]
This lib didn't parse config file, you should parse it by yourself.
