### ISSUE TITLE
shell seems doesn't callback

### ISSUE THREAD

**Issue by soonlive** [teambition/gulp-ssh#42]
hi @zensh ,

I'm using gulp-ssh to exec a shell in order to unarchive files. But it seems doesn't work correctly.

As you can see, it just pause there
![image](https://cloud.githubusercontent.com/assets/6039369/13169177/8b0a5d58-d71e-11e5-93a9-7df08676a339.png)

and the following is my config:
![image](https://cloud.githubusercontent.com/assets/6039369/13169224/ed681c38-d71e-11e5-8cbd-c04c9daa4d20.png)

Could you figure out how to make it work?

**Comment by zensh** [comment]
did the command ran in remote?

**Comment by soonlive** [comment]
yep, it did

**Comment by mickaelperrin** [comment]
Hi, @soonlive regarding your code, I am maybe wrong but it seems your lacking a `return`statement at the beginning of the testSSH line ?

However, @zensh I encounter a similar problem when using gulp-ssh as an external module with a modular gulp approach.

I have created a specific repository https://github.com/mickaelperrin/gulp-ssh-error to give you a way to reproduce the error.

See the README in my repository for additionnal informations on how to run the test and the problem I encounter.

Hope it helps.

**Comment by zensh** [comment]
@mickaelperrin Thank you for your PR. It happened because of using different gulp instance.

**Comment by mickaelperrin** [comment]
Thanks for taking time to explore my problem.

I just gave a try to the new release 0.5.6, but didn't notify any changes in the behaviour.

Would you mind taking a look [at the update my demo](https://github.com/mickaelperrin/gulp-ssh-error/commit/19c2d4b84fa2cc616734b400adb9886053b53fc8), to see what's wrong with my code ?

**Comment by mickaelperrin** [comment]
Mmm, got it new gulp option is not a suboption of sshConfig. Sorry for busying you with that.
