### ISSUE TITLE
dest command transfer all folders to remote?

### ISSUE THREAD

**Issue by csonlai** [teambition/gulp-ssh#44]
return gulp
        .src(paths.dist.dir + '*.html')
        .pipe(gulpSSH.dest(paths.build.htmlDir));

as result,it transfer all folders to remote, not just the html files,
for example:
[17:33:40] Finished writing '/xx/x/remote_dir/d:/project/src/xx.html 

how could i only transfer the html files to remote? thx

**Comment by csonlai** [comment]
this bug only happen in windows file system,i think this will fix it:
    getSftp(function (err, sftp) {
      if (err) return end(err, callback)
 **     file.base = file.base.replace(/\\/g,'/'); //solve bug in windows**
      var baseRegexp = new RegExp('^' + file.base.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, '\\$&'))
      var outPath = path.join(destDir, file.path.replace(baseRegexp, '')).replace(/\\/g, '/')

**Comment by zensh** [comment]
You can try to add a filter stream between src and dest

**Comment by csonlai** [comment]
can filter stream change the file.base?
