### ISSUE TITLE
Remote files are written with absolute local path

### ISSUE THREAD

**Issue by t3rminus** [teambition/gulp-ssh#56]
When uploading using gulpSSH.dest, the remote path includes the entire local path.

So a project stored at 
`/home/user/projects/api/index.js`
`/home/user/projects/api/lib/util.js`

gets deployed to the remote `dest('/home/user/api')` as
 `/home/user/api/home/user/projects/api/index.js`
`/home/user/api/home/user/projects/api/lib/util.js`

instead of just
`/home/user/api/index.js`
`/home/user/api/lib/util.js`

Example:

``` javascript
gulp.task('deploy:staging:copy', function(){
    return gulp
        .src(['**/*'], { base: './' })
        .pipe(gulpSSH.dest('/home/user/api'));
});
```

I made a temporary work-around by adding a stream filter, as mentioned in #44 , which switches the file path for the relative file path:

``` javascript
gulp.task('deploy:staging:copy', function(){
    return gulp
        .src(['**/*'], { base: './' })
        .pipe(require('stream-filter').obj(function(file) {
            file.path = file.relative;
            return file;
        }))
        .pipe(gulpSSH.dest('/home/user/api'));
});
```

But this seems inefficient and contrary to what is expected.

**Comment by mojavelinux** [comment]
I agree that gulp-ssh should be using file.relative [like vinyl-fs](https://github.com/gulpjs/vinyl-fs/blob/master/lib/dest/prepare.js#L30) instead trying to [manually relativize](https://github.com/teambition/gulp-ssh/blob/master/index.js#L245-L246) the file.

I'll propose a change.
