### ISSUE TITLE
Question: Executing global modules?

### ISSUE THREAD

**Issue by vernak2539** [teambition/gulp-ssh#57]
I've been trying to execute commands of global modules. Examples being npm and pm2. Both are installed on the host.

I've tried all of the following commands, but none have worked. When logging into the machine, these commands work

`npm install --production`, `pm2 start`, `$(which pm2) start`

Errors: 
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: bash: npm: command not found
```

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: bash: pm2: command not found
```

**Comment by zensh** [comment]
please use `shell()`
```js
gulp.task('shell', function () {
  return gulpSSH
    .shell(['cd /home/iojs/test/thunks', 'git pull', 'npm install', 'npm update', 'npm test'], {filePath: 'shell.log'})
    .pipe(gulp.dest('logs'))
})
```

**Comment by vernak2539** [comment]
that worked, thank you @zensh
