### ISSUE TITLE
sftp read/write all files in folder

### ISSUE THREAD

**Issue by dennisbaum** [teambition/gulp-ssh#9]
is it possible to read all files in a folder, or better read/copy a folder recursive with all subfolder/subfiles via sftp? i tried different *-combination or {recursive:true} as options, but that did not work.
btw: which options are available by the sftp-api (command, filePath, options)?
Tnx.

**Comment by zensh** [comment]
I suggest you using gulp-rsync to upload a folder. sftp-api can only read or write one file.

**Comment by dennisbaum** [comment]
i will, thanks for clarification

**Comment by zensh** [comment]
Hi, `0.5.0` released, add 'dest' that write files to remote

**Comment by thebuilder** [comment]
Cool, the new **dest** works great! :+1:
